# Generated by Django 6.1 on 2026-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='education_logos/'),
        ),
    ]
